# Generated by Django 5.1.1 on 2024-09-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده '),
        ),
    ]
