# Generated by Django 5.0.7 on 2024-10-01 05:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ اضافه شدن'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ  '),
        ),
    ]
