# Generated by Django 5.0.7 on 2024-10-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_created_data_alter_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price_mandeh',
            field=models.BigIntegerField(default=0, verbose_name='باقی مانده در فروشگاه'),
        ),
        migrations.AddField(
            model_name='customer',
            name='price_paid',
            field=models.BigIntegerField(default=0, verbose_name=' پول پردخات شده  '),
        ),
    ]
