# Generated by Django 5.0.7 on 2024-10-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_price_mandeh_customer_price_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price_paid_all',
            field=models.BigIntegerField(default=0, verbose_name='کل پرداخت شده ها '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='price_paid',
            field=models.BigIntegerField(default=0, verbose_name=' پول  پرداختی لحظه ای   '),
        ),
    ]
