# Generated by Django 5.1.1 on 2024-10-01 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customer_price_paid_all_alter_customer_price_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='price_paid',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='price_paid_all',
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.BigIntegerField(default=0, verbose_name=' پول  پرداختی لحظه ای   ')),
                ('price_paid_all', models.BigIntegerField(default=0, verbose_name=' پول  پرداختی  ای کل    ')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ  ')),
                ('created_data', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پرداخت  ',
                'verbose_name_plural': 'لیست پرداخت ها ',
            },
        ),
    ]
