# Generated by Django 5.1.1 on 2024-10-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_customer_price_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='discription',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات مدیر'),
        ),
    ]
