# Generated by Django 5.1.1 on 2024-10-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_payments_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='price_paid_all',
        ),
        migrations.AddField(
            model_name='customer',
            name='price_paid_all',
            field=models.BigIntegerField(default=0, verbose_name=' پول  پرداختی  ای کل    '),
        ),
    ]
