# Generated by Django 5.1.1 on 2024-10-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_payments_price_paid_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='شماره تماس'),
        ),
    ]
