# Generated by Django 5.1.1 on 2024-10-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='created_data',
        ),
    ]
