# Generated by Django 5.1.1 on 2024-10-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_remove_payments_created_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='created_data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ اضافه شدن'),
        ),
    ]
