# Generated by Django 5.1.1 on 2024-10-02 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت خرید'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_selling',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت فروش'),
        ),
        migrations.CreateModel(
            name='AvailableProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mojodi', models.PositiveBigIntegerField(default=0, verbose_name='موجودی')),
                ('discription', models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات مدیر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'موجودی محصول',
                'verbose_name_plural': 'موجودی محصولات  ',
            },
        ),
    ]
