# Generated by Django 5.1.1 on 2024-10-02 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_availableproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='AvailableProduct',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
