# Generated by Django 5.1.1 on 2024-10-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_created=True, blank=True, null=True, verbose_name='تاریخ افزودن محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='mojidi',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sod',
            field=models.BigIntegerField(default=0),
        ),
    ]
