# Generated by Django 5.1.1 on 2024-10-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_created_at_product_mojidi_product_sod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ افزودن محصول'),
        ),
    ]
