# Generated by Django 5.1.1 on 2024-10-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_availableproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproduct',
            name='price_kol',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
