# Generated by Django 5.1.1 on 2024-10-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_availableproduct_price_kol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availableproduct',
            options={'verbose_name': 'خرید  محصول', 'verbose_name_plural': 'خرید  محصولات  '},
        ),
    ]
