# Generated by Django 5.1.1 on 2024-10-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproduct',
            name='created_at',
            field=models.DateField(auto_created=True, blank=True, null=True, verbose_name='تاریخ افزودن محصول'),
        ),
    ]
