# Generated by Django 5.1.1 on 2024-10-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_availableproduct_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableproduct',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ افزودن محصول'),
        ),
    ]
