# Generated by Django 5.1.1 on 2024-09-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_shop',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام فروشگاه شما '),
        ),
    ]
