# Generated by Django 5.1.1 on 2024-09-30 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_name_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'فروشگاه', 'verbose_name_plural': 'فروشگاه ها '},
        ),
    ]
