# Generated by Django 5.1.1 on 2024-10-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
