# Generated by Django 5.1.1 on 2024-10-05 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0011_alter_customer_phone'),
        ('product', '0012_alter_availableproduct_options'),
        ('sale', '0002_delete_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tedad', models.BigIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ افزودن محصول')),
                ('price_kol', models.BigIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش ها ',
            },
        ),
    ]
