# Generated by Django 5.1.1 on 2024-10-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='created_at',
        ),
    ]
