# Generated by Django 5.1.1 on 2024-10-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_remove_sale_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ اضافه شدن'),
        ),
    ]
